services:
  - type: web
    name: news-dedup-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /ping
    envVars:
      - key: SIM_RATIO
        value: "0.82"
      - key: JACCARD
        value: "0.60"
      - key: DESC_WIDTH
        value: "160" 