services:
  - type: web
    name: news-dedup-topk
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/ping"
    autoDeploy: true
    envVars:
      - key: SIM_RATIO
        value: "0.82"
      - key: JACCARD
        value: "0.60"
      - key: TOPK
        value: "3"            # ✅ 기본 Top 3
      - key: FETCH_BY_LINK
        value: "true"
      - key: MAX_FETCH
        value: "12"
      - key: HTTP_TIMEOUT
        value: "5.0"
      - key: MAX_BYTES
        value: "800000"
      - key: USER_AGENT
        value: "Mozilla/5.0 (compatible; NewsDedupBot/1.0)"
